<?php

namespace TNM\PCRF\Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Orchestra\Testbench\TestCase as BaseTestCase;
use TNM\PCRF\Providers\PCRFServiceProvider;


class TestCase extends BaseTestCase
{
//    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Config::set('pcrf.timeout', 10);
        \Config::set('pcrf.trans_id.length', 32);
        \Config::set('pcrf.trans_id.prefix', 'SMA');
    }

    protected function getPackageProviders($app): array
    {
        return [PCRFServiceProvider::class];
    }

}
